### ISSUE TITLE
Terminal does not have expected width when focused.

### ISSUE THREAD

**Issue by testmad** [mitosch/textual-terminal#4]
When starting the Terminal focused, the emulator will have the default width/height being set by ncol/nrow. If you do not set the focus or set_focus(None) when starting the terminal, it will be at the full width.

**Comment by testmad** [comment]
Found a solution:
```
terminal.start()
self.set_focus(terminal)
terminal.post_message(Resize(size=self.size, virtual_size=self.size))
```

**Comment by mitosch** [comment]
Thank you for reporting this issue. I'll look into it and try to implement it into to plugin.

**Comment by mitosch** [comment]
I close this issue because the Terminal Widget should not change it's size unexpected. The implementing application is responsible for setting the size of the terminal.
